name: admin_panel
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.6.0

dependencies:
  flutter:
    sdk: flutter
  provider: ^6.1.2
  cupertino_icons: ^1.0.2
  flutter_secure_storage: ^9.0.0
  fluttertoast: ^8.2.4
  http: ^1.2.0
  another_flushbar: ^1.12.30
  cached_network_image: ^3.3.1
  get_it: ^7.6.7
  shared_preferences: ^2.2.2
  freezed: ^2.4.6
  freezed_annotation: ^2.4.1
  json_annotation: ^4.8.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
